python/qemu-ga-client: add exec command
This invokes guest-exec and guest-exec-status (repeatedly if needed),
copying stdin/stdout/stderr/exitcode to and from the guest agent.

Since file descriptor data is not streamed, stdin is only read if not a
TTY (and is fully read before starting the GA invocation).  Similarly
stdout is written out in its entirety, followed by stderr.

Samples:

	$ scripts/qmp/qemu-ga-client exec id
	uid=0(root) gid=0(root) groups=0(root)
	$ scripts/qmp/qemu-ga-client exec ls -- -C
	bin   dev  home  lib32  libx32      media  opt   root  sbin  srv  tmp  var
	boot  etc  lib   lib64  lost+found  mnt    proc  run   snap  sys  usr
	$ scripts/qmp/qemu-ga-client exec true ; echo $?
	0
	$ scripts/qmp/qemu-ga-client exec false ; echo $?
	1
	$ scripts/qmp/qemu-ga-client exec -- sh -c 'echo out; echo err >&2'  2>/dev/null
	out
	$ scripts/qmp/qemu-ga-client exec -- sh -c 'echo out; echo err >&2'  >/dev/null
	err
	$ scripts/qmp/qemu-ga-client exec -- ls -l /proc/self/fd
	total 0
	lr-x------ 1 root root 64 Dec 20 07:37 0 -> /dev/null
	l-wx------ 1 root root 64 Dec 20 07:37 1 -> pipe:[19288]
	l-wx------ 1 root root 64 Dec 20 07:37 2 -> pipe:[19289]
	lr-x------ 1 root root 64 Dec 20 07:37 3 -> /proc/1428/fd
	$ scripts/qmp/qemu-ga-client exec -- ls -l /proc/self/fd < /etc/issue
	total 0
	lr-x------ 1 root root 64 Dec 20 07:37 0 -> pipe:[19301]
	l-wx------ 1 root root 64 Dec 20 07:37 1 -> pipe:[19302]
	l-wx------ 1 root root 64 Dec 20 07:37 2 -> pipe:[19303]
	lr-x------ 1 root root 64 Dec 20 07:37 3 -> /proc/1430/fd
	$ scripts/qmp/qemu-ga-client exec -- od -tcx1 < /etc/issue
	0000000   U   b   u   n   t   u       2   0   .   0   4   .   6       L
	         55  62  75  6e  74  75  20  32  30  2e  30  34  2e  36  20  4c
	0000020   T   S       \   n       \   l  \n  \n
	         54  53  20  5c  6e  20  5c  6c  0a  0a
	0000032

	$ scripts/qmp/qemu-ga-client exec bork
	...
	qemu.qmp.qmp_client.ExecuteError: Guest agent command failed, error was 'Failed to execute child process “bork” (No such file or directory)'

Signed-off-by: Alex Badea <vamposdecampos@gmail.com>